apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
  labels:
    app: kubernetes-service-label
spec:
  type: NodePort
  selector:
    app: kubernetes-deployment-selector
  ports:
    - port: 80
      targetPort: 8085
      protocol: TCP
      nodePort: 32225