apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment-selector
  template:
    metadata:
      labels:
        app: postgres-deployment-selector
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: kubernetes-config-map
                  key: DB_CONNECTION_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kubernetes-config-map
                  key: DB_CONNECTION_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: kubernetes-config-map
                  key: DB_CONNECTION_DATABASE